#!/bin/bash

# This is a simple script to create and setup a Python Flask API project with my personal preferences of configuration.
# Feel free to use it as you need to automate your projects creations.

folder_name=$1;

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

RED=`tput setaf 1`;
reset=`tput sgr0`;


echo "${RED}Creating Backend Application${reset}";
mkdir $folder_name;
cd $folder_name;


echo "${RED}Creating Python environment${reset}";
python3 -m virtualenv venv;
# This is for a windows machine/ version for windows virtualenv; 
# If you are using mac or linux you can substitute "Scripts" for "bin". 
source venv/Scripts/activate;
pip install flask;
pip install flask_restful;
pip install flask_cors;

echo "${RED}Creating folder structure${reset}";
mkdir ./src;
cd src;
mkdir controller; 
mkdir model;
cd ..;


echo "${RED}Writing boylerplate files.${reset}";
cp ${SCRIPTPATH}/backend_boilerplate/controller.py ./src/controller/controller.py;
cp ${SCRIPTPATH}/backend_boilerplate/controller.__init__.py ./src/controller/__init__.py;
cp ${SCRIPTPATH}/backend_boilerplate/model.__init__.py ./src/model/__init__.py;
cp ${SCRIPTPATH}/backend_boilerplate/app.py ./app.py;



